---
title: "SPAN MRI Analytics Pilot Data Report: An Inter-site Comparison of Quantitative Parameters Maps"
author: "Ryan P. Cabeen"
date: "2020-09-30"
header-includes:
- \usepackage{booktabs}
- \usepackage{makecell}
output: 
  pdf_document:
    keep_tex: true
editor_options: 
  chunk_output_type: console
---

```{r setup, message=FALSE, warning=FALSE, error=FALSE, echo=FALSE}
library(stargazer)
library(ggplot2)
library(gridExtra)
library(xtable)
library(papeR)
library(scales)
library(ggplot2)

df <- read.csv("histograms.csv")
df$site <- df$site_dicom

t2fitLow <- 12.5
t2fitHigh <- 40

t2harmLow <- 0.15 
t2harmHigh <- 1.5 

adcfitLow <- 0.0001
adcfitHigh <- 0.002

adcharmLow <- 0.01
adcharmHigh <- 3 
```

```{r plot_all_t2_rate_share, message=FALSE, warning=FALSE, error=FALSE, echo=FALSE, fig.height=10, fig.width=7}
subdf <- df[df$type == "fit" & df$param == "t2_rate",];
fit.plot <- ggplot(data=subdf, aes(x=name, y=value, color=site, group=site)) + xlim(t2fitLow,t2fitHigh) + geom_point(alpha=0.15)  + geom_smooth(span=0.1) + xlab("Raw T2 Rate (reciprocal)") + ylab("Voxel Count") + ggtitle("Raw T2 Star Parameters Across Sites")
subdf <- df[df$type == "harm" & df$param == "t2_rate",];
harm.plot <- ggplot(data=subdf, aes(x=name, y=value, color=site, group=site)) + xlim(t2harmLow,t2harmHigh) + geom_point(alpha=0.15)  + geom_smooth(span=0.1) + xlab("Harmonized T2 Rate (reciprocal)") + ylab("Voxel Count") + ggtitle("Harmonized T2 Star Parameters Across Sites")

grid.arrange(fit.plot, harm.plot, nrow = 2)
```

```{r plot_all_adc_rate_share, message=FALSE, warning=FALSE, error=FALSE, echo=FALSE, fig.height=10, fig.width=7}
subdf <- df[df$type == "fit" & df$param == "adc_rate",];
fit.plot <- ggplot(data=subdf, aes(x=name, y=value, color=site, group=site)) + xlim(adcfitLow,adcfitHigh) + geom_point(alpha=0.15)  + geom_smooth(span=0.1) + xlab("Raw ADC") + ylab("Voxel Count") + ggtitle("Raw ADC Across Sites")
subdf <- df[df$type == "harm" & df$param == "adc_rate",];
harm.plot <- ggplot(data=subdf, aes(x=name, y=value, color=site, group=site)) + xlim(adcharmLow,adcharmHigh) + geom_point(alpha=0.15)  + geom_smooth(span=0.1) + xlab("Harmonized ADC") + ylab("Voxel Count") + ggtitle("Harmonized ADC Across Sites")

grid.arrange(fit.plot, harm.plot, nrow = 2)
```

```{r plot_all_t2_rate_fit_sites, message=FALSE, warning=FALSE, error=FALSE, echo=FALSE, fig.height=10, fig.width=7}
subdf <- df[df$type == "fit" & df$param == "t2_rate",];
plot1 <- ggplot(data=subdf[subdf$site == "Augusta_University",], aes(x=name, y=value, group=subject)) + xlim(t2fitLow,t2fitHigh) + geom_point(alpha=0.15)  + geom_smooth(span=0.1) + xlab("Raw T2 Rate (reciprocal)") + ylab("Voxel Count") + ggtitle("Raw T2 Star Parameters from Augusta")
plot2 <- ggplot(data=subdf[subdf$site == "Yale_University",], aes(x=name, y=value, group=subject)) + xlim(t2fitLow,t2fitHigh) + geom_point(alpha=0.15)  + geom_smooth(span=0.1) + xlab("Raw T2 Rate (reciprocal)") + ylab("Voxel Count") + ggtitle("Raw T2 Star Parameters from Yale University")
plot3 <- ggplot(data=subdf[subdf$site == "Kennedy_Krieger_Institute",], aes(x=name, y=value, group=subject)) + xlim(t2fitLow,t2fitHigh) + geom_point(alpha=0.15)  + geom_smooth(span=0.1) + xlab("Raw T2 Rate (reciprocal)") + ylab("Voxel Count") + ggtitle("Raw T2 Star Parameters from JHU")
plot4 <- ggplot(data=subdf[subdf$site == "University_of_Iowa",], aes(x=name, y=value, group=subject)) + xlim(t2fitLow,t2fitHigh) + geom_point(alpha=0.15)  + geom_smooth(span=0.1) + xlab("Raw T2 Rate (reciprocal)") + ylab("Voxel Count") + ggtitle("Raw T2 Star Parameters from Iowa")
plot5 <- ggplot(data=subdf[subdf$site == "DII_UT_Health",], aes(x=name, y=value, group=subject)) + xlim(t2fitLow,t2fitHigh) + geom_point(alpha=0.15)  + geom_smooth(span=0.1) + xlab("Raw T2 Rate (reciprocal)") + ylab("Voxel Count") + ggtitle("Raw T2 Star Parameters from Texas")
plot6 <- ggplot(data=subdf[subdf$site == "MGH",], aes(x=name, y=value, group=subject)) + xlim(t2fitLow,t2fitHigh) + geom_point(alpha=0.15)  + geom_smooth(span=0.1) + xlab("Raw T2 Rate (reciprocal)") + ylab("Voxel Count") + ggtitle("Raw T2 Star Parameters from MGH")

grid.arrange(plot1, plot2, plot3, plot4, plot5, plot6, ncol=1, nrow=6)
```

```{r plot_all_t2_rate_harm_sites, message=FALSE, warning=FALSE, error=FALSE, echo=FALSE, fig.height=10, fig.width=7}
subdf <- df[df$type == "harm" & df$param == "t2_rate",];
plot1 <- ggplot(data=subdf[subdf$site == "Augusta_University",], aes(x=name, y=value, group=subject)) + xlim(t2harmLow,t2harmHigh) + geom_point(alpha=0.15)  + geom_smooth(span=0.1) + xlab("Harmonized T2 Rate (reciprocal)") + ylab("Voxel Count") + ggtitle("Harmonized T2 Star Parameters from Augusta")
plot2 <- ggplot(data=subdf[subdf$site == "Yale_University",], aes(x=name, y=value, group=subject)) + xlim(t2harmLow,t2harmHigh) + geom_point(alpha=0.15)  + geom_smooth(span=0.1) + xlab("Harmonized T2 Rate (reciprocal)") + ylab("Voxel Count") + ggtitle("Harmonized T2 Star Parameters from Yale University")
plot3 <- ggplot(data=subdf[subdf$site == "Kennedy_Krieger_Institute",], aes(x=name, y=value, group=subject)) + xlim(t2harmLow,t2harmHigh) + geom_point(alpha=0.15)  + geom_smooth(span=0.1) + xlab("Harmonized T2 Rate (reciprocal)") + ylab("Voxel Count") + ggtitle("Harmonized T2 Star Parameters from JHU")
plot4 <- ggplot(data=subdf[subdf$site == "University_of_Iowa",], aes(x=name, y=value, group=subject)) + xlim(t2harmLow,t2harmHigh) + geom_point(alpha=0.15)  + geom_smooth(span=0.1) + xlab("Harmonized T2 Rate (reciprocal)") + ylab("Voxel Count") + ggtitle("Harmonized T2 Star Parameters from Iowa")
plot5 <- ggplot(data=subdf[subdf$site == "DII_UT_Health",], aes(x=name, y=value, group=subject)) + xlim(t2harmLow,t2harmHigh) + geom_point(alpha=0.15)  + geom_smooth(span=0.1) + xlab("Harmonized T2 Rate (reciprocal)") + ylab("Voxel Count") + ggtitle("Harmonized T2 Star Parameters from Texas")
plot6 <- ggplot(data=subdf[subdf$site == "MGH",], aes(x=name, y=value, group=subject)) + xlim(t2harmLow,t2harmHigh) + geom_point(alpha=0.15)  + geom_smooth(span=0.1) + xlab("Harmonized T2 Rate (reciprocal)") + ylab("Voxel Count") + ggtitle("Harmonized T2 Star Parameters from MGH")

grid.arrange(plot1, plot2, plot3, plot4, plot5, plot6, ncol=1, nrow=6)
```

```{r plot_all_adc_rate_fit_sites, message=FALSE, warning=FALSE, error=FALSE, echo=FALSE, fig.height=10, fig.width=7}
subdf <- df[df$type == "fit" & df$param == "adc_rate",];
plot1 <- ggplot(data=subdf[subdf$site == "Augusta_University",], aes(x=name, y=value, group=subject)) + xlim(adcfitLow,adcfitHigh) + geom_point(alpha=0.15)  + geom_smooth(span=0.1) + xlab("Raw ADC") + ylab("Voxel Count") + ggtitle("Raw ADC from Augusta")
ploadc <- ggplot(data=subdf[subdf$site == "Yale_University",], aes(x=name, y=value, group=subject)) + xlim(adcfitLow,adcfitHigh) + geom_point(alpha=0.15)  + geom_smooth(span=0.1) + xlab("Raw ADC") + ylab("Voxel Count") + ggtitle("Raw ADC from Yale University")
plot3 <- ggplot(data=subdf[subdf$site == "Kennedy_Krieger_Institute",], aes(x=name, y=value, group=subject)) + xlim(adcfitLow,adcfitHigh) + geom_point(alpha=0.15)  + geom_smooth(span=0.1) + xlab("Raw ADC") + ylab("Voxel Count") + ggtitle("Raw ADC from JHU")
plot4 <- ggplot(data=subdf[subdf$site == "University_of_Iowa",], aes(x=name, y=value, group=subject)) + xlim(adcfitLow,adcfitHigh) + geom_point(alpha=0.15)  + geom_smooth(span=0.1) + xlab("Raw ADC") + ylab("Voxel Count") + ggtitle("Raw ADC from Iowa")
plot5 <- ggplot(data=subdf[subdf$site == "DII_UT_Health",], aes(x=name, y=value, group=subject)) + xlim(adcfitLow,adcfitHigh) + geom_point(alpha=0.15)  + geom_smooth(span=0.1) + xlab("Raw ADC") + ylab("Voxel Count") + ggtitle("Raw ADC from Texas")
plot6 <- ggplot(data=subdf[subdf$site == "MGH",], aes(x=name, y=value, group=subject)) + xlim(adcfitLow,adcfitHigh) + geom_point(alpha=0.15)  + geom_smooth(span=0.1) + xlab("Raw ADC") + ylab("Voxel Count") + ggtitle("Raw ADC from MGH")

grid.arrange(plot1, ploadc, plot3, plot4, plot5, plot6, ncol=1, nrow=6)
```

```{r plot_all_adc_rate_harm_sites, message=FALSE, warning=FALSE, error=FALSE, echo=FALSE, fig.height=10, fig.width=7}
subdf <- df[df$type == "harm" & df$param == "adc_rate",];
plot1 <- ggplot(data=subdf[subdf$site == "Augusta_University",], aes(x=name, y=value, group=subject)) + xlim(adcharmLow,adcharmHigh) + geom_point(alpha=0.15)  + geom_smooth(span=0.1) + xlab("Harmonized ADC") + ylab("Voxel Count") + ggtitle("Harmonized ADC from Augusta")
ploadc <- ggplot(data=subdf[subdf$site == "Yale_University",], aes(x=name, y=value, group=subject)) + xlim(adcharmLow,adcharmHigh) + geom_point(alpha=0.15)  + geom_smooth(span=0.1) + xlab("Harmonized ADC") + ylab("Voxel Count") + ggtitle("Harmonized ADC from Yale University")
plot3 <- ggplot(data=subdf[subdf$site == "Kennedy_Krieger_Institute",], aes(x=name, y=value, group=subject)) + xlim(adcharmLow,adcharmHigh) + geom_point(alpha=0.15)  + geom_smooth(span=0.1) + xlab("Harmonized ADC") + ylab("Voxel Count") + ggtitle("Harmonized ADC from JHU")
plot4 <- ggplot(data=subdf[subdf$site == "University_of_Iowa",], aes(x=name, y=value, group=subject)) + xlim(adcharmLow,adcharmHigh) + geom_point(alpha=0.15)  + geom_smooth(span=0.1) + xlab("Harmonized ADC") + ylab("Voxel Count") + ggtitle("Harmonized ADC from Iowa")
plot5 <- ggplot(data=subdf[subdf$site == "DII_UT_Health",], aes(x=name, y=value, group=subject)) + xlim(adcharmLow,adcharmHigh) + geom_point(alpha=0.15)  + geom_smooth(span=0.1) + xlab("Harmonized ADC") + ylab("Voxel Count") + ggtitle("Harmonized ADC from Texas")
plot6 <- ggplot(data=subdf[subdf$site == "MGH",], aes(x=name, y=value, group=subject)) + xlim(adcharmLow,adcharmHigh) + geom_point(alpha=0.15)  + geom_smooth(span=0.1) + xlab("Harmonized ADC") + ylab("Voxel Count") + ggtitle("Harmonized ADC from MGH")

grid.arrange(plot1, ploadc, plot3, plot4, plot5, plot6, ncol=1, nrow=6)
```

